services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./foxford_test_case:/foxford_test_case
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass
      - DJANGO_SETTINGS_MODULE=foxford_test_case.settings


    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - database

  database:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass

  redis:
    image: redis:7.0.5-alpine
    hostname: redis

  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A foxford_test_case worker --beat --scheduler django --loglevel=info

    volumes:
      - ./foxford_test_case:/foxford_test_case
    links:
      - redis
    depends_on:
      - redis
      - database
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass
      - DJANGO_SETTINGS_MODULE=foxford_test_case.settings


  flower:
    build:
      context: .
    hostname: flower
    entrypoint: celery
    command: -A foxford_test_case flower
    volumes:
      - ./foxford_test_case:/foxford_test_case
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "5555:5555"


