# Generated by Django 4.1.5 on 2023-03-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_app', '0005_alter_salary_hours_alter_salary_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='hours',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
    ]
