# Generated by Django 4.1.5 on 2023-03-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_app', '0006_webinar_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
