# Generated by Django 4.1.5 on 2023-03-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_app', '0007_alter_webinar_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='teachers',
            field=models.ManyToManyField(related_name='webinars', to='study_app.teacher'),
        ),
    ]
