# Generated by Django 4.1.5 on 2023-03-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_app', '0008_alter_webinar_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
